id: PD3C0593E
initial_creation_type: ocr
source_metadata:
  volumes:
    21a86dc8d0d84218a4e93d29de32bb09:
      base_file: v042.txt
      image_group_id: I1PD95887
      title: ''
      total_pages: 1712
      volume_number: 42
